In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.impute import SimpleImputer
import os
from pync import Notifier


df = pd.read_csv('../csv/merged_data.csv')

numerical_features = ['temp','visibility','dew_point','feels_like','pressure','humidity','wind_speed','wind_deg','wind_gust','rain_1h','snow_1h','clouds_all','weather_id', 'year','month','day']
X = df[numerical_features]
y = df['aqi_cat']

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = imputer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Initialize the KNN classifier
# You can adjust 'n_neighbors' based on your specific needs or use cross-validation to find an optimal value
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the model to the training data
knn.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn.predict(X_test)

# Use the say command for spoken text notification
Notifier.notify('Your notebook has finished running.', title='Notification')
os.system('say "Your notebook has finished running."')

/var/folders/6m/1wyk0cv146d91z1nsb6cxh6w0000gn/T/ipykernel_2611/2237424313.py:12: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../csv/merged_data.csv')


0

In [2]:
# Evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))


Confusion Matrix:
 [[195523   1772      0      9      0]
 [  5284   2548      0     71      0]
 [     6      0      0      0      0]
 [   284    164      0     78      0]
 [     1      0      0      0      0]]


/Users/mollynelson/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/mollynelson/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/mollynelson/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Classification Report:
                                 precision    recall  f1-score   support

                          Good       0.97      0.99      0.98    197304
                      Moderate       0.57      0.32      0.41      7903
                     Unhealthy       0.00      0.00      0.00         6
Unhealthy for Sensitive Groups       0.49      0.15      0.23       526
                Very Unhealthy       0.00      0.00      0.00         1

                      accuracy                           0.96    205740
                     macro avg       0.41      0.29      0.32    205740
                  weighted avg       0.96      0.96      0.96    205740

Accuracy Score: 0.9631039175658598


In [3]:
from sklearn.inspection import permutation_importance
import matplotlib as plt
result = permutation_importance(knn, X, y, n_repeats=10, random_state=42)

# Plot the importance
plt.figure()
plt.title("Permutation Feature Importance")
plt.bar(range(X.shape[1]), result.importances_mean, yerr=result.importances_std)
plt.xticks(range(X.shape[1]), range(X.shape[1]))
plt.show()